# headless service to avoid deletion of patronidemo-config endpoint
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-config
  namespace: patroni
  labels:
    application: patroni
    cluster-name: patronidemo
spec:
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: &cluster_name patronidemo
  namespace: patroni
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-primary
  namespace: patroni
  labels:
    application: patroni
    cluster-name: patronidemo
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    application: patroni
    cluster-name: patronidemo
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-lb
  namespace: patroni
  labels:
    application: patroni
    cluster-name: patronidemo
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    application: patroni
    cluster-name: patronidemo
    role: primary
  ports:
  - port: 5432
    targetPort: 6432
---
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-lb
  namespace: patroni
  labels:
    application: patroni
    cluster-name: patronidemo
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    application: patroni
    cluster-name: patronidemo
    role: primary
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-repl
  namespace: patroni
  labels:
    application: patroni
    cluster-name: &cluster_name patronidemo
    role: replica
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    application: patroni
    cluster-name: *cluster_name
    role: replica
